"""Build the offline full-text search index for AI Mastery Docs.

Author: Sanat -- For My Wife Okin

Scans every HTML page under the site root, splits each page into sections at
<h1>/<h2>/<h3>, and writes assets/js/search-index.js as a plain JS global so the
site can search from file:// without fetch().

Usage:  python tools/build_search_index.py
"""
from __future__ import annotations

import html
import json
import re
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "js" / "search-index.js"
SKIP_TAGS = {"script", "style", "svg", "nav", "header"}


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


class Sectioner(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.in_content = False
        self.depth = 0
        self.skip = 0
        self.heading: str | None = None
        self.head_id: str | None = None
        self.head_buf: list[str] = []
        self.sections: list[dict] = []
        self.buf: list[str] = []
        self.cur = {"s": "", "a": ""}
        self.title = ""
        self.in_title = False

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag == "title":
            self.in_title = True
        if tag == "article" and a.get("id") == "content":
            self.in_content = True
            self.depth = 0
        if not self.in_content:
            return
        self.depth += 1
        if tag in SKIP_TAGS:
            self.skip += 1
        if tag in ("h1", "h2", "h3") and not self.skip:
            self.heading = tag
            self.head_id = a.get("id")
            self.head_buf = []

    def handle_endtag(self, tag):
        if tag == "title":
            self.in_title = False
        if not self.in_content:
            return
        if tag in SKIP_TAGS and self.skip:
            self.skip -= 1
        if self.heading == tag:
            self.flush()
            text = " ".join("".join(self.head_buf).split())
            anchor = "" if tag == "h1" else (self.head_id or slug(text))
            self.cur = {"s": text, "a": anchor}
            self.heading = None
        self.depth -= 1
        if tag == "article" and self.depth <= 0:
            self.flush()
            self.in_content = False

    def handle_data(self, data):
        if self.in_title:
            self.title += data
        if not self.in_content or self.skip:
            return
        if self.heading:
            self.head_buf.append(data)
        else:
            self.buf.append(data)

    def flush(self):
        text = " ".join(" ".join(self.buf).split())
        if text and self.cur["s"]:
            self.sections.append({**self.cur, "x": text[:4000]})
        self.buf = []


def main() -> None:
    entries = []
    for path in sorted(ROOT.rglob("*.html")):
        rel = path.relative_to(ROOT).as_posix()
        p = Sectioner()
        p.feed(path.read_text(encoding="utf-8"))
        page_title = html.unescape(p.title.split("|")[0].strip())
        seen: dict[str, int] = {}
        for s in p.sections:
            a = s["a"]
            if a:
                n = seen.get(a, 0)
                seen[a] = n + 1
                if n:
                    a = f"{a}-{n + 1}"
            entries.append({"p": page_title, "u": rel, "s": s["s"], "a": a, "x": s["x"]})
    OUT.write_text(
        "/* Generated by tools/build_search_index.py -- do not edit. Author: Sanat */\n"
        "window.SEARCH_INDEX = " + json.dumps(entries, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"Indexed {len(entries)} sections from {len({e['u'] for e in entries})} pages -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
